spring.datasource.url=jdbc:postgresql://ep-icy-glitter-am7xnm0p-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XvUfjHOQY4V7
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=omengine
spring.flyway.enabled=true
spring.flyway.default-schema=omengine
spring.flyway.locations=classpath:db/migration
spring.application.name=omengine
groq.api.key=${GROQ_API_KEY}
server.port=${PORT:8080}