spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=omengine
spring.flyway.enabled=true
spring.flyway.default-schema=omengine
spring.flyway.locations=classpath:db/migration
spring.application.name=omengine
groq.api.key=${GROQ_API_KEY}
server.port=${PORT:8080}